import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ActionButton } from '../components/ActionButton'
import { api } from '../lib/api'
import { formatDate, formatDuration } from '../lib/format'
import type { QueueAdjacentResponse, SettingsResponse, VideoDetail } from '../types'

const SAVE_INTERVAL_MS = 5000

export function PlayerPage() {
  const { videoId } = useParams(); const [searchParams] = useSearchParams(); const view = searchParams.get('view') || 'unfinished'; const navigate = useNavigate(); const videoRef = useRef<HTMLVideoElement | null>(null)
  const [video, setVideo] = useState<VideoDetail | null>(null); const [settings, setSettings] = useState<SettingsResponse | null>(null); const [adjacent, setAdjacent] = useState<QueueAdjacentResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  useEffect(() => { let active = true; async function load() { setLoading(true); setError(null); try { const settingsResponse = await api.getSettings(); if (active) setSettings(settingsResponse); let targetId = videoId; if (!targetId) { const response = await api.getContinue(); targetId = response.video?.id ?? undefined; if (!targetId) throw new Error('No unfinished videos remain.'); navigate(`/review/${targetId}`, { replace: true }); return } const detail = await api.getVideo(targetId, view); const adjacentResponse = await api.getAdjacent(targetId, view); if (!active) return; setVideo(detail); setAdjacent(adjacentResponse) } catch (err) { if (active) setError(err instanceof Error ? err.message : 'Failed to load video') } finally { if (active) setLoading(false) } } void load(); return () => { active = false } }, [videoId, navigate, view])
  useEffect(() => { if (!video || !videoRef.current) return; void api.resumePlayback(video.id).then((resume) => { if (videoRef.current && resume.position_seconds > 0) videoRef.current.currentTime = resume.position_seconds }).catch(() => undefined) }, [video?.id])
  useEffect(() => { const timer = window.setInterval(() => { if (!videoRef.current || !video) return; void api.savePlayback(video.id, { position_seconds: videoRef.current.currentTime, duration_seconds: Number.isFinite(videoRef.current.duration) ? videoRef.current.duration : null, event: 'progress', current: true }) }, SAVE_INTERVAL_MS); return () => window.clearInterval(timer) }, [video])
  const goToVideo = (targetId: string | null) => { if (targetId) navigate(`/review/${targetId}?view=${view}`) }
  const handleStatus = async (reviewState: 'queued' | 'watched' | 'skipped', bookmarked?: boolean) => { if (!video) return; const payload: Record<string, unknown> = { review_state: reviewState, current: true }; if (typeof bookmarked === 'boolean') payload.bookmarked = bookmarked; if (videoRef.current) payload.playback_position_seconds = videoRef.current.currentTime; const updated = await api.updateVideoStatus(video.id, payload); setVideo(updated); if (reviewState === 'watched' && settings?.auto_advance_on_done) { if (adjacent?.next_video_id) navigate(`/review/${adjacent.next_video_id}?view=${view}`); else navigate('/') } }
  const handleEnded = async () => { if (!video || !videoRef.current) return; await api.savePlayback(video.id, { position_seconds: videoRef.current.currentTime, duration_seconds: Number.isFinite(videoRef.current.duration) ? videoRef.current.duration : null, event: 'ended', current: true }); if (settings?.auto_advance_on_end && adjacent?.next_video_id) navigate(`/review/${adjacent.next_video_id}?view=${view}`) }
  const handlePause = async () => { if (!video || !videoRef.current) return; await api.savePlayback(video.id, { position_seconds: videoRef.current.currentTime, duration_seconds: Number.isFinite(videoRef.current.duration) ? videoRef.current.duration : null, event: 'pause', current: true }) }
  const handleError = async () => { if (!video) return; await api.savePlayback(video.id, { position_seconds: videoRef.current?.currentTime ?? 0, duration_seconds: Number.isFinite(videoRef.current?.duration) ? videoRef.current?.duration : null, event: 'load_error', current: true }); setError('The browser could not load this file. You can skip it and continue.') }
  const queueLabel = useMemo(() => !video ? '—' : !video.position_in_queue ? `of ${video.queue_total}` : `${video.position_in_queue} of ${video.queue_total}`, [video])
  return <div className="stack-gap">{loading ? <div className="card">Loading player…</div> : null}{error ? <div className="error-banner">{error}</div> : null}{video ? <><section className="card player-card"><video ref={videoRef} src={video.stream_url} controls playsInline autoPlay preload="metadata" onEnded={() => void handleEnded()} onPause={() => void handlePause()} onError={() => void handleError()} /></section><section className="card info-grid"><div><div className="meta-label">Filename</div><div className="meta-value truncate">{video.filename}</div></div><div><div className="meta-label">Queue position</div><div className="meta-value">{queueLabel}</div></div><div><div className="meta-label">Sort date</div><div className="meta-value">{formatDate(video.derived_sort_date)}</div></div><div><div className="meta-label">Sort source</div><div className="meta-value">{video.derived_sort_source ?? 'unknown'}</div></div><div><div className="meta-label">Duration</div><div className="meta-value">{formatDuration(video.duration_seconds)}</div></div><div><div className="meta-label">Resume point</div><div className="meta-value">{formatDuration(video.playback_position_seconds)}</div></div></section><section className="button-grid large-grid"><ActionButton label="Previous" onClick={() => goToVideo(adjacent?.previous_video_id ?? null)} disabled={!adjacent?.previous_video_id} /><ActionButton label="Next" onClick={() => goToVideo(adjacent?.next_video_id ?? null)} disabled={!adjacent?.next_video_id} /><ActionButton label="Done" tone="success" onClick={() => void handleStatus('watched')} /><ActionButton label="Skip" tone="danger" onClick={() => void handleStatus('skipped')} /><ActionButton label={video.bookmarked ? 'Unbookmark' : 'Bookmark'} onClick={() => void handleStatus(video.review_state, !video.bookmarked)} /><ActionButton label="Resume" tone="primary" onClick={() => { if (videoRef.current) videoRef.current.play().catch(() => undefined) }} /></section></> : null}</div>
}
