import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ActionButton } from '../components/ActionButton'
import { api } from '../lib/api'
import { formatDuration, formatMonthKey, formatShortDate } from '../lib/format'
import type { PaginatedVideosResponse } from '../types'

const VIEWS = ['unfinished', 'all', 'watched', 'skipped', 'bookmarked'] as const

export function TimelinePage() {
  const navigate = useNavigate(); const [view, setView] = useState<typeof VIEWS[number]>('unfinished'); const [page, setPage] = useState(1); const [month, setMonth] = useState(''); const [jumpDate, setJumpDate] = useState(''); const [jumpPosition, setJumpPosition] = useState(''); const [data, setData] = useState<PaginatedVideosResponse | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; async function load() { setLoading(true); setError(null); try { const params = new URLSearchParams({ view, page: String(page), page_size: '60' }); if (month) { const [yearValue, monthValue] = month.split('-'); params.set('year', yearValue); params.set('month', monthValue) } const response = await api.listVideos(params); if (active) setData(response) } catch (err) { if (active) setError(err instanceof Error ? err.message : 'Failed to load timeline') } finally { if (active) setLoading(false) } } void load(); return () => { active = false } }, [view, page, month])
  const grouped = useMemo(() => { const groups = new Map<string, PaginatedVideosResponse['items']>(); for (const item of data?.items ?? []) { const key = formatMonthKey(item.derived_sort_date); const list = groups.get(key) ?? []; list.push(item); groups.set(key, list) } return Array.from(groups.entries()) }, [data])
  const handleJump = async () => { const params = new URLSearchParams({ view }); if (jumpDate) params.set('jump_date', jumpDate); if (jumpPosition) params.set('position', jumpPosition); const result = await api.jump(params); if (result.video_id) navigate(`/review/${result.video_id}?view=${view}`) }
  return <div className="stack-gap"><section className="card filters-grid"><label><span>View</span><select value={view} onChange={(e) => { setView(e.target.value as typeof VIEWS[number]); setPage(1) }}>{VIEWS.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label><span>Filter month</span><input type="month" value={month} onChange={(e) => { setMonth(e.target.value); setPage(1) }} /></label><label><span>Jump to date</span><input type="date" value={jumpDate} onChange={(e) => setJumpDate(e.target.value)} /></label><label><span>Jump to item #</span><input type="number" min="1" value={jumpPosition} onChange={(e) => setJumpPosition(e.target.value)} /></label><div className="filter-actions"><ActionButton label="Go" tone="primary" onClick={() => void handleJump()} /><ActionButton label="Clear" onClick={() => { setMonth(''); setJumpDate(''); setJumpPosition(''); setPage(1) }} /></div></section>{loading ? <div className="card">Loading timeline…</div> : null}{error ? <div className="error-banner">{error}</div> : null}{grouped.map(([groupLabel, items]) => <section key={groupLabel} className="stack-gap"><h2 className="section-heading">{groupLabel}</h2><div className="grid-list">{items.map((item) => <button key={item.id} className="card video-card" onClick={() => navigate(`/review/${item.id}?view=${view}`)}><div className="thumb-shell">{item.thumbnail_url ? <img src={item.thumbnail_url} alt="thumbnail" loading="lazy" /> : <div className="thumb-placeholder">No thumb</div>}</div><div className="video-card-body"><div className="video-title">{item.filename}</div><div className="video-meta">{formatShortDate(item.derived_sort_date)} · {formatDuration(item.duration_seconds)}</div><div className="video-badges"><span className="badge">{item.review_state}</span>{item.bookmarked ? <span className="badge">bookmarked</span> : null}{item.derived_sort_source ? <span className="badge">{item.derived_sort_source}</span> : null}</div></div></button>)}</div></section>)}{data ? <section className="card pager-row"><div>Page {data.page} of {data.total_pages} · {data.total_items} items</div><div className="hero-actions"><ActionButton label="Previous page" onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page <= 1} /><ActionButton label="Next page" onClick={() => setPage((p) => p + 1)} disabled={page >= data.total_pages} /></div></section> : null}</div>
}
